### ISSUE TITLE
Chat box not showing up

### ISSUE THREAD

**Issue by haar09** [oldventura/kgbtr-chatroom#31]
Connecting from iphone 5s any browser. when i join i cant see messages i sent and received. Tested on every browser installed on the phone. Started after new theme.

**Comment by haar09** [comment]
Issue 31 kxlsndmdmd

**Comment by oldventura** [comment]
> Issue 31 kxlsndmdmd

puhahahahahahaa

**Comment by oldventura** [comment]
Aga test ettim cihazda, baksana bende böyle görünüyor:
<img src="https://i.imgur.com/5rqezLA.png">
<img src="https://i.imgur.com/ph03I8K.png">
<img src="https://i.imgur.com/ufZeuPl.png">
<img src="https://i.imgur.com/IrRlhaR.png">

**Comment by oldventura** [comment]
Dostum sorunu tekrarlayamıyorum, o nedenle şimdilik bunu kapatıyorum. Eğer sorununla ilgili daha fazla bilgi bulabilirsen lütfen tekrar aç.
