### ISSUE TITLE
Toplu Paket

### ISSUE THREAD

**Issue by BeypazariMadenSuyu** [oldventura/kgbtr-chatroom#6]
-Chate mesaj yazılınca belli bir süre cooldown verilebilir.
-Chatte karışıklık olmaması için büyük/küçük harf uyumu yok sayılarak aynı nickte insanların engellenmesi sağlanabilir.
-Site arkaplanına KGBTR ile alakalı bir görsel konulabilir.
-Parola özelliği gelebilir.

**Comment by oldventura** [comment]
Parola var ama herkese açık değil :)

**Comment by oldventura** [comment]
Cooldown özelliğini ekledim. 2. ve 4. yazdıklarını çözmesi için direkt reddit login'i ekleyeceğim. Özelliği ekleyince bu issue'yu kapatırım.

**Comment by oldventura** [comment]
Reddit login'ini ekledik, arkaplan olayı için ayrı issue açıyorum.
