### ISSUE TITLE
bir flood paneli

### ISSUE THREAD

**Issue by galiyevZ** [oldventura/kgbtr-chatroom#9]
Sadece belirli kişilerin erişim sağlayabileceği, içinde çeşitli floodların olduğu bir panel

**Comment by oldventura** [comment]
kanka üzgünüm ama bunu eklemeyi düşünmüyorum. Şimdilik kapatıyorum, ilerde tekrar düşünüp bakarız ama bana bu site için gereksiz geldi kusura bakma.
